/* tslint:disable */
/* eslint-disable */
/**
 * Salus Management API
 * This API exposes endpoints to manage Salus' Entities
 *
 * OpenAPI spec version: 1.0
 * Contact: alessandro-giordano@fullstack-group.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosError } from 'axios'
import { ErrorMessage } from './models';

globalAxios.interceptors.response.use(response => response, (error: AxiosError<ErrorMessage>) => {
  if (error.response && error.response.status > 399 && error.response.status < 500) {
    window.dispatchEvent(new CustomEvent('axios-error', {detail: error.response.data.message}))
  }
  return Promise.reject(error)
})

export * from "./api";
export * from "./configuration";
export * from "./models";

